# SPDX-FileCopyrightText: 2022 Mirek Długosz <mirek@mirekdlugosz.com>
#
# SPDX-License-Identifier: CC0-1.0

name: CD
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
